---
- block:
  - name: generating build files
    template:
      src: "{{ item }}"
      dest: "{{ build_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - ../templates/build/*.j2
  tags:
    - configure
    - build
